import OfferSection from '@/components/display/offerSection/OfferSection';
import TeamIntro from '@/components/display/teamIntro/TeamIntro';
import Hero from '@/components/hero/Hero';
import Head from 'next/head';

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <main>
        <Hero />
        <OfferSection />
        <TeamIntro />
      </main>
    </>
  );
}
